/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author pauli
 */
public class ProgrammeurVue extends JFrame implements ActionListener {

    private JPanel panel;
    private JButton btnRechercher;
    private JButton btnReinitialiser;
    private JButton btnValider;
    private JButton btnAnnuler;
    private JLabel labelMatricule;
    private JTextField champMatricule; 
    private JLabel labelNom;
    private JTextField champNom; 
    private JLabel labelPrenom;
    private JTextField champPrenom; 
    private JLabel labelAdresse;
    private JTextField champAdresse; 
    private JLabel labelPseudo;
    private JTextField champPseudo; 
    private JLabel labelResponsable;
    private JTextField champResponsable; 
    private JLabel labelHobby;
    private JTextField champHobby; 
    private JLabel labelDate_naiss;
    private JTextField champDate_naiss; 
    private JLabel labelDate_emb;
    private JTextField champDate_emb; 
    
    public void init(){
        panel = new JPanel();
        btnRechercher = new JButton("Rechercher");
        btnReinitialiser = new JButton("Réinitialiser");
        btnValider = new JButton("Valider");
        btnAnnuler = new JButton("Annuler");
        labelMatricule = new JLabel("Matricule");
        champMatricule = new JTextField();
        champMatricule.setColumns(10);
        labelNom = new JLabel("Nom");
        champNom = new JTextField();
        champNom.setColumns(10);
        labelPrenom = new JLabel("Prénom");
        champPrenom = new JTextField();
        champPrenom.setColumns(10);
        labelAdresse = new JLabel("Adresse");
        champAdresse = new JTextField();
        champAdresse.setColumns(10);
        labelPseudo = new JLabel("Pseudo");
        champPseudo = new JTextField();
        champPseudo.setColumns(10);
        labelResponsable = new JLabel("Responsable");
        champResponsable = new JTextField();
        champResponsable.setColumns(10);
        labelHobby = new JLabel("Hobby");
        champHobby = new JTextField();
        champHobby.setColumns(10);
        labelDate_naiss = new JLabel("Date de naissance");
        champDate_naiss = new JTextField();
        champDate_naiss.setColumns(10);
        labelDate_emb = new JLabel("Date d'embauche");
        champDate_emb = new JTextField();
        champDate_emb.setColumns(10);
        
        /** Tous les widgets sont placés sur le panel
         * Et après le panel est "posé" sur notre frame de base
         */        
        panel.add(btnRechercher);
        panel.add(btnReinitialiser);
        panel.add(btnValider);
        panel.add(btnAnnuler);
        panel.add(labelMatricule);
        panel.add(champMatricule);
        panel.add(labelNom);
        panel.add(champNom);
        panel.add(labelPrenom);
        panel.add(champPrenom);
        panel.add(labelAdresse);
        panel.add(champAdresse);
        panel.add(labelPseudo);
        panel.add(champPseudo);
        panel.add(labelResponsable);
        panel.add(champResponsable);
        panel.add(labelHobby);
        panel.add(champHobby);
        panel.add(labelDate_naiss);
        panel.add(champDate_naiss);
        panel.add(labelDate_emb);
        panel.add(champDate_emb);
        
        btnValider.addActionListener(this);
        
        /**
         * Par défaut, notre frame n'est pas visible
         * Il faut donc forcer la visibilité à "true"
         */
        this.setVisible(true);
        this.setTitle("GesProg");
        setDefaultCloseOperation(EXIT_ON_CLOSE); // Fermeture fenêtre = arrêt de l'application 
        setBounds(10, 10, 600, 300);

        this.add(panel); // Ajout du panel à notre frame de base
    }
    
    /**
     * Creates new form ProgrammeurVue
     */
    public ProgrammeurVue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgrammeurVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgrammeurVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgrammeurVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgrammeurVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgrammeurVue().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
